swagger: "3.0.0"
basePath: /api/v1
tags:
  - name: Product
    description: The Product API
paths:
  /api/v1/products/save:
    post:
      summary: Add product
      description: Add a new product.
      tags:
        - Product
      security:
        - apiKey: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Product"
      responses:
        201:
          description: Successfully added a new product
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Successfully added a new product"
        400:
          description: Bad request, Invalid user input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized, Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        409:
          description: Conflict, A product exists with the same name
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
/api/v1/products/list:
    get:
      summary: Get products
      description: Get products based on a particular category
      tags:
        - Product
      security:
        - apiKey: []
      parameters:
      - name: categoryId
        in: query
        description: id of the category 
        required: false
        schema:
          type: string
          default: 8977475d-f549-412e-95b7-383e069bf310
      responses:
        200:
          description: Successfully retrieved products based on the category
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: "success"
                  message:
                    type: string
                    example: "Successfully retrieved products by category"
                  data:
                    type: object
                    properties:
                     categoryId:
                      type: string
                      example: 8977475d-f549-412e-95b7-383e069bf310
                     categoryName:
                      example: Footwear
                     totalProducts:
                      type: number,
                      example: 10
                     products:
                      type: array    
                      items:        
                        $ref: "#/components/schemas/Product"
        400:
          description: Bad request, Invalid user input
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        401:
          description: Unauthorized, Invalid credentials
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Product:
      type: object
      required:
        - productName
        - price
        - productImage
        - brand
        - categoryId
      properties:
        productId:
          type: string 
          description: The auto-generated id of every category
          readOnly: true
        productName:
          type: string
          description: Name of the product
          example: "Jack and Jones Leather boots"
        price:
          type: number
          description: price for the product
          example: 4000
        productImage:
          type: string
          description: Image url of the product
          example: https://m.media-amazon.com/images/I/71ZLToAJrYL._AC_UY1000_.jpg
        brand:
          type: string
          description: Product brand name
          example: Jack and Jones
        categoryId:
          type: string
          description: Id of the category where the product belongs to 
          example: 8977475d-f549-412e-95b7-383e069bf310
    ErrorResponse:
      type: object
      required:
        - status
        - message
      properties:
        status:
          type: string
          example: "error"
        message:
          type: string
          example: "An error occurred"

  securitySchemes:
    apiKey:
      type: apiKey
      in: header
      name: x-api-key
  